test: include replace.hpp explicit
This patch will be needed when we move the boost version to avobe
1.56.0. Actually, this patch doesn't affect current boost version
because the header will be automatically included by other header.

../../../src/test/tools.h:70:2: error: 'replace_all' is not a member of
'boost'
boost::replace_all(result, "wfits::", "");

Change-Id: I0648af0f4e3f3d565700eca7ceb3d8167adeeaad
Signed-off-by: Chanho Park <chanho61.park@samsung.com>